### ISSUE TITLE
ShortLivedConnectionsRecipe: using perf_warmup_duration for neper tcp_crr tests results in exception

### ISSUE THREAD

**Issue by jtluka** [LNST-project/lnst#260] opened 2022-10-27 15:17 UTC
This was detected in downstream testing however should be applicable to upstream as well.

The traceback:
```
Traceback (most recent call last):
  File "/mnt/tests/gitlab.cee.redhat.com/lnst-team/beaker-tasks/-/archive/master/beaker-tasks-master.tar.gz/lnst/test-runner/./do-my-test", line 38, in main
    ctl.run(recipe)
  File "/root/virtualenvs/rhextensions-lnst-Xo1BSm3a-py3.9/lib/python3.9/site-packages/lnst/Controller/Controller.py", line 172, in run
    recipe.test()
  File "/root/rhextensions-lnst/lnst/RHExtensions/RHRecipeMixin.py", line 80, in test
    super(RHRecipeMixin, self).test()
  File "/root/virtualenvs/rhextensions-lnst-Xo1BSm3a-py3.9/lib/python3.9/site-packages/lnst/Recipes/ENRT/BaseEnrtRecipe.py", line 172, in test
    self.do_tests(recipe_config)
  File "/root/virtualenvs/rhextensions-lnst-Xo1BSm3a-py3.9/lib/python3.9/site-packages/lnst/Recipes/ENRT/BaseEnrtRecipe.py", line 294, in do_tests
    self.do_perf_tests(recipe_config)
  File "/root/virtualenvs/rhextensions-lnst-Xo1BSm3a-py3.9/lib/python3.9/site-packages/lnst/Recipes/ENRT/BaseEnrtRecipe.py", line 320, in do_perf_tests
    self.perf_report_and_evaluate(result)
  File "/root/virtualenvs/rhextensions-lnst-Xo1BSm3a-py3.9/lib/python3.9/site-packages/lnst/RecipeCommon/Perf/Recipe.py", line 191, in perf_report_and_evaluate
    aligned_results = results.time_aligned_results
  File "/root/virtualenvs/rhextensions-lnst-Xo1BSm3a-py3.9/lib/python3.9/site-packages/lnst/RecipeCommon/Perf/Recipe.py", line 123, in time_aligned_results
    real_times = self._get_measurement_timestamps(iteration_results_group)
  File "/root/virtualenvs/rhextensions-lnst-Xo1BSm3a-py3.9/lib/python3.9/site-packages/lnst/RecipeCommon/Perf/Recipe.py", line 108, in _get_measurement_timestamps
    return flows[-1].warmup_end, flows[-1].warmdown_start
  File "/root/virtualenvs/rhextensions-lnst-Xo1BSm3a-py3.9/lib/python3.9/site-packages/lnst/RecipeCommon/Perf/Measurements/BaseFlowMeasurement.py", line 226, in warmup_end
    [
  File "/root/virtualenvs/rhextensions-lnst-Xo1BSm3a-py3.9/lib/python3.9/site-packages/lnst/RecipeCommon/Perf/Measurements/BaseFlowMeasurement.py", line 227, in <listcomp>
    parallel[self.warmup_duration - 1].end_timestamp
IndexError: list index out of range
```

The ShortLivedConnectionsRecipe recipe parameters:
```
driver='mlx4_en';perf_duration=60;perf_tool_cpu=[0];dev_intr_cpu=[0];adaptive_tx_coalescing=True;adaptive_rx_coalescing=True;ip_versions=['ipv4'];perf_tests=['tcp_crr'];perf_msg_sizes=[1024];rx_pause_frames=False;tx_pause_frames=False;disable_turboboost=True;minimal_idlestates_latency=0;drop_caches=True;save_sosreport=False;perf_warmup_duration=3
```

**Comment by enhaut** [comment] 2022-10-31 09:40
I think this is not a bug, `perf_warmup_duration` is implemented for `iperf` only. Thats because neper flow is not meant to be "as constant as iperf": 

![flow_n_neper](https://user-images.githubusercontent.com/34833780/198977788-2252dc73-57d2-454e-b35f-2ba651317537.png)
iperf flow:  
![flow_t](https://user-images.githubusercontent.com/34833780/198978093-d7831662-4ddf-478c-8c7c-1c353ff0c45e.png)

I'd say the problem is, that lnst tries to trip flow that does not support that

**Comment by jtluka** [comment] 2022-10-31 10:17
I think the problem is that there's a difference in the data generated by neper's tcp_rr and tcp_crr. The later one does not generate any data at all, see neper commit https://github.com/google/neper/commit/6d0f6599688ede3b8e31f0cec99a14ef5369b96a.

The `perf_warmup_duration` works fine for the tcp_rr case.

**Comment by jtluka** [comment] 2022-10-31 12:28
Here's LNST specific code that deals with neper's flaw: https://github.com/LNST-project/lnst/blob/master/lnst/RecipeCommon/Perf/Measurements/NeperFlowMeasurement.py#L178

**Comment by enhaut** [comment] 2022-10-31 14:47
Discussed offline, got a fix ready, @jtluka pls assign this issue to me.

**Closed** 2022-12-07 12:09 UTC
