### ISSUE TITLE
allow to implement python-only recipes

### ISSUE THREAD

**Issue by jpirko** [LNST-project/lnst#143] opened 2015-08-11 14:37 UTC
It is a great thing that we have python tasks. Another step into this direction would be to have python recipes. I can imagine couple of formats:

A) lnst-ctl will get python recipe on file and instead of processing xml recipe, it will execute python recipe. That recipe would be provided with classes needed to define machines, interfaces, etc.
B) python recipe would be executed directly. It will prepare recipe (machine,addr,etc, definitions) function and task function. This 2 functions will be passed to some special LNST class that will do all the work.

I like B a lot. Downside is that we loose whole command line parameters infra. I think that we should support both A and B. Needed infrastructure would easily support both.

**Comment by jiriprochazka** [comment] 2015-10-21 08:57
```
from lnst.Controller.Task import ctl
#
m1 = ctl.add_host("machine1")
m2 = ctl.add_host("machine2")

#
m1_testiface = m1.add_interface(
                "type" : "eth",
                "id" : "testiface",
                "label" : "testnet",
                "addresses" : [
                        "192.168.101.10/24",
                        "2002::1/64"
                        ]
               )
m2_testiface = m2.add_interface(
                "type" : "eth",
                "id" : "testiface",
                "label" : "testnet",
                "addresses" : [
                        "192.168.101.11/24",
                        "2002::2/64"
                        ]
               )

#
while ctl.match_and_configure():

    m1.sync_resources(modules=["Icmp6Ping", "IcmpPing"])
    m2.sync_resources(modules=["Icmp6Ping", "IcmpPing"])

    m1_testiface.set_mtu(mtu)
    m2_testiface.set_mtu(mtu)

    ping_mod = ctl.get_module("IcmpPing",
                               options={
                                  "addr": m2_testiface.get_ip(0),
                                  "count": 100,
                                  "interval": 0.2,
                                  "iface" : m1_testiface.get_devname(),
                                  "limit_rate": 90})

    ping_mod6 = ctl.get_module("Icmp6Ping",
                               options={
                                  "addr": m2_testiface.get_ip(1),
                                  "count": 100,
                                  "interval": 0.2,
                                  "iface" : m1_testiface.get_ip(1),
                                  "limit_rate": 90})

    ctl.wait(15)

    ipv = ctl.get_alias("ipv")
    mtu = ctl.get_alias("mtu")


    if ipv in [ 'ipv6', 'both' ]:
        m1.run(ping_mod6)

    if ipv in [ 'ipv4', 'both' ]:
        m1.run(ping_mod)
```

**Comment by jiriprochazka** [comment] 2015-10-21 09:52
Another example of python recipe network setup, for 3_vlans test from phase1 regression tests. The test part is omitted, since it's the same as in the current python task.

```Python
from lnst.Controller.Task import ctl
from lnst.Controller.PerfRepoUtils import netperf_baseline_template
from lnst.Controller.PerfRepoUtils import netperf_result_template

# Host setup
m1 = ctl.add_host("m1")
m2 = ctl.add_host("m2")

# Interface setup
# m1 eth1
m1_eth1 = m1.add_interface(
            i_type="eth",
            i_id="eth1"
            label="tnet"
        )

# m1 vlan10
m1_vlan10 = m1.add_interface(
            i_type="vlan",
            i_id="vlan10",
            vlan_tci="10"
        )
m1_vlan10.add_addresses(["192.168.10.1/24", "2002::10:1/64"])
m1_vlan10.add_slave(m1_eth1)

# m1 vlan20
m1_vlan20 = m1.add_interface(
            i_type="vlan",
            i_id="vlan20",
            vlan_tci="20"
        )
m1_vlan20.add_addresses(["192.168.20.1/24", "2002::20:1/64"])
m1_vlan20.add_slave(m1_eth1)

# m1 vlan30
m1_vlan30 = m1.add_interface(
            i_type="vlan",
            i_id="vlan30",
            vlan_tci="30"
        )
m1_vlan30.add_addresses(["192.168.30.1/24", "2002::30:1/64"])
m1_vlan30.add_slave(m1_eth1)

# m2 eth1
m2_eth1 = m2.add_interface(
            i_type="eth",
            i_id="eth1"
            label="tnet"
        )

# m2 vlan10
m2_vlan10 = m2.add_interface(
            i_type="vlan",
            i_id="vlan10",
            vlan_tci="10"
        )

m2_vlan10.add_addresses(["192.168.10.2/24", "2002::10:2/64"])
m2_vlan10.add_slave(m2_eth1)

# m2 vlan20
m2_vlan20 = m2.add_interface(
            i_type="vlan",
            i_id="vlan20",
            vlan_tci="20"
        )

m2_vlan20.add_addresses(["192.168.20.2/24", "2002::20:2/64"])
m2_vlan20.add_slave(m2_eth1)

# m2 vlan30
m2_vlan30 = m2.add_interface(
            i_type="vlan",
            i_id="vlan30",
            vlan_tci="30"
        )

m2_vlan30.add_addresses(["192.168.30.2/24", "2002::30:2/64"])
m2_vlan30.add_slave(m2_eth1)
```

**Comment by olichtne** [comment] 2015-11-16 13:49
I think this is a good start, I think both formats should be available. I would lean more to the first example to how we should try to write our recipes, but I want the second option for special situations where we might not know everything we need to know.

About the match_and_configure() method, I think the parameter "once" should be supplied from the lnst-ctl call and shouldn't be part of the recipe...

**Comment by olichtne** [comment] 2021-08-16 07:36
closing as not relevant anymore...

**Closed by olichtne** 2021-08-16 07:36 UTC
Labels: enhancement
